force-app/main/default/objects/CB_Subscription__c/CB_Subscription__c.object-meta.xml
<CustomObject>
    <description>CB Subscriptions</description>
    <label>CB Subscription</label>
    <nameField>
        <label>CB Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Subscription</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CB_Subscription__c/fields/CB_Id__c.field-meta.xml
<CustomField>
    <fullName>CB_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>CB Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>Chargebee Coupon</description>
    <label>CB Coupon</label>
    <nameField>
        <label>Coupon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon__c/fields/CB_Id__c.field-meta.xml
<CustomField>
    <fullName>CB_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Chargebee coupon id</description>
    <externalId>true</externalId>
    <label>CB Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Coupon_Id__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Coupon Id</description>
    <externalId>true</externalId>
    <label>Coupon Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coupon_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Product type</description>
    <inlineHelpText>Product Type as classified in Chargebee</inlineHelpText>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADDON</fullName>
            </value>
            <value>
                <fullName>PLAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CB Status</description>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateSub.cls
public class UpdateSub{

    public Map<String,Object> mp{get;set;}
    public BaseEstimateController cont{get;set;}
    public String cbId{get;set;}
    
    public String oldPlan{get;set;}
    public String oldPlanCur{get;set;}
    public Integer oldPlanQuan{get;set;}
    public Integer oldPlanPrice{get;set;}
    public Integer oldPlanSetUp{get;set;}
    public String coupId{get;set;}
    public boolean invNow{get;set;}
    public List<SelectOption> optionsInvoiceNow{get;set;}
    
    public BaseError errObj{get;set;}
    public CB_Subscription__c sub{get;set;}

    public List<SelectOption> planOpts{
    get
    {
      List<PricebookEntry> prodList = new List<PricebookEntry>();
      prodList = [Select id,Product2.ExternalId,product2.name From PricebookEntry  where Pricebook2.Name='CB Standard' and product2.Status__c='ACTIVE' and product2.Product_Type__c='PLAN' limit 500];
      prodList.sort();
      planOpts = new List<SelectOption>();
      planOpts.add(new SelectOption('-1','Select'));
      for(PricebookEntry temp : prodList){
        if(temp.Product2.ExternalId!= null){
          planOpts.add(new SelectOption(temp.Product2.ExternalId,temp.Product2.name));
        }
      }
      planOpts = CBSubscriptionUtil.sortSelectOptions(planOpts);
      return planOpts;
    }
    set;
    }
    
    public List<SelectOption> coupenOptions {
    get{
      List<Coupon__c> prodList = new List< Coupon__c>();
      
      prodList = [Select Coupon_Id__c,Name,Status__c From Coupon__c where Status__c = 'ACTIVE' limit 500];
      coupenOptions = new List<SelectOption>();
      coupenOptions.add(new SelectOption('-1','Select'));
      for(Coupon__c temp : prodList){
        if(temp.Coupon_Id__c != null){
          coupenOptions.add(new SelectOption(temp.Coupon_Id__c,temp.name));
        }
      }
      coupenOptions = CBSubscriptionUtil.sortSelectOptions(coupenOptions);
      return coupenOptions;
    }
    set;
    }
    
    public UpdateSub(){
        
        sub = [select Id,CB_Id__c from CB_Subscription__c where Id=:'a0J2800000JDA7h'];
        if(sub.CB_Id__c==null){
            errObj = new BaseError('This subscription is not present in Chargebee.');
        }
        URLBuilder ub = new URLBuilder(EndPointsIndex.retrieve_sub_url);
        ub.ustring='gfdgd';
        cont = new RetSubController(ub);
        mp = cont.makeRequest();
        errObj = new BaseError(mp);
        SubRespObj subResp = new SubRespObj((Map<String,Object>)mp.get('subscription'));
        oldPlan=subResp.getPlanId();
        oldPlanCur=subResp.getCurCode();
        oldPlanPrice=subResp.getPlanUnitPrice();
        oldPlanQuan=subResp.getPlanQuan();
        oldPlanSetUp=subResp.getPlanSetupFee();
        coupId=subResp.getCouponId();
        optionsInvoiceNow = new List<SelectOption>();
        optionsInvoiceNow.add(new SelectOption('true','Invoice now'));
        optionsInvoiceNow.add(new SelectOption('false','Add to unbilled charges'));
        invNow=true;
        System.debug('coupId---'+coupId);       
    }
    
    public void start(){
    
         UpdateSubUrlBuilder usub = new UpdateSubUrlBuilder();
         usub.Id(cbId).planId('new1');
         cont = new UpdateSubEstController(usub);
         cont.setEndPoint(EndPointsIndex.update_est_url);
         mp = cont.makeRequest();
         
    }
}