force-app/main/default/objects/chargebee__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>API Keys are essential when you have to authenticate while trying to connect to Chargebee&#39;s API.

You can find your API keys in the web interface under Settings &gt; API and Webhooks &gt; API Keys</description>
    <inlineHelpText>API Keys are essential when you have to authenticate your session while trying to connect to Chargebee&#39;s API.

You can find your API keys in the web interface under Settings &gt; API and Webhooks &gt; API Keys</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/chargebee__c/fields/ChargeBee_URL__c.field-meta.xml
<CustomField>
    <fullName>ChargeBee_URL__c</fullName>
    <description>The portal url for chargebee</description>
    <label>ChargeBee URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/chargebee__c/fields/Settings_JSON__c.field-meta.xml
<CustomField>
    <fullName>Settings_JSON__c</fullName>
    <description>All chargebee site settings and configurations in JSON</description>
    <label>Settings JSON</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/RequestMaker.cls
public class RequestMaker{
    
    public URLBuilder builder{get;set;}
    private Map<String,Object> resp;
    private boolean is_err;
    private static chargebee__c mhc;
    
    public RequestMaker(){
        is_err=false;
        fetchSettings();
    }
    
    public RequestMaker(URLBuilder ub){
        builder=ub;
        is_err=false;
        fetchSettings();
    }
    
    private void fetchSettings(){
        if(mhc==null){
            mhc=chargebee__c.getOrgDefaults();
        }
        
    }
    
    public void setBuilder(URLBuilder ub){
        builder=ub;
    }
    
    public String getUrl()
    {
        return mhc.ChargeBee_URL__c;
    }

    public String getApiKey()
    {
        return mhc.API_Key__c;
    }

    public String getSiteSettingJSON()
    {
        return mhc.Settings_JSON__c;
    }

    
    public Map<String,Object> makeRequest(){
        HttpRequest reqData = new HttpRequest();
        Http http = new Http();
        
        reqData.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        reqData.setHeader('Connection','keep-alive');
        reqData.setTimeout(20000);
        
        
        if(builder.getReqType().toLowerCase().equals('get')){
            reqData.setEndpoint(builder.getEndpointUrl()+builder.build());
        }else if(builder.getReqType().toLowerCase().equals('post')){
            reqData.setEndpoint(builder.getEndpointUrl());
        } 
        
        
        String username = getApiKey();
        System.debug('key-->>>'+username);
        Blob headerValue = Blob.valueOf(username + ':');
        String authorizationHeader = 'BASIC ' +
        EncodingUtil.base64Encode(headerValue);
        reqData.setHeader('Authorization', authorizationHeader);             
        reqData.setMethod(builder.getReqType());
        
        if(builder.getReqType().toLowerCase().equals('post')){
            reqData.setBody(builder.build());
        }
        
        String response;  
        HTTPResponse res = http.send(reqData);
        response = res.getBody();
        resp = CBURLUtil.convertMap(response);
        if(resp.get('error_msg')!=null){
            this.is_err=true;
        }
        return resp;
    }
    
    public boolean isError(){
        return is_err;
    }
    
    public BaseError getErrorObject(){
        return new BaseError(resp); 
    }

}