force-app/main/default/objects/chargebee__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>API Keys are essential when you have to authenticate while trying to connect to Chargebee&#39;s API.

You can find your API keys in the web interface under Settings &gt; API and Webhooks &gt; API Keys</description>
    <inlineHelpText>API Keys are essential when you have to authenticate your session while trying to connect to Chargebee&#39;s API.

You can find your API keys in the web interface under Settings &gt; API and Webhooks &gt; API Keys</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/chargebee__c/fields/ChargeBee_URL__c.field-meta.xml
<CustomField>
    <fullName>ChargeBee_URL__c</fullName>
    <description>The portal url for chargebee</description>
    <label>ChargeBee URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/chargebee__c/fields/Settings_JSON__c.field-meta.xml
<CustomField>
    <fullName>Settings_JSON__c</fullName>
    <description>All chargebee site settings and configurations in JSON</description>
    <label>Settings JSON</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/chargebee__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <description>Chargebee Username</description>
    <inlineHelpText>Chargebee Username</inlineHelpText>
    <label>User Name</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Chargebee_Config__c/Chargebee_Config__c.object-meta.xml
<CustomObject>
    <label>Chargebee Config</label>
    <nameField>
        <label>Chargebee Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chargebee Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chargebee_Config__c/fields/CB_Primary__c.field-meta.xml
<CustomField>
    <fullName>CB_Primary__c</fullName>
    <description>Primary query condition for Chargebee</description>
    <label>CB Primary</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Chargebee_Config__c/fields/ChargeBee_URL__c.field-meta.xml
<CustomField>
    <fullName>ChargeBee_URL__c</fullName>
    <description>Chargebee connected site URL</description>
    <label>ChargeBee_URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Config__c/fields/Settings_JSON__c.field-meta.xml
<CustomField>
    <fullName>Settings_JSON__c</fullName>
    <description>Settings_JSON</description>
    <label>Settings_JSON</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/chargebee_settings__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <label>User_Name</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/ChargeBeeSettingController.cls
public with sharing class ChargeBeeSettingController {

 public CustomSettingProxy setting{get; set;}
 public String overRideAllowed{get;set;}
 public String autoCollection{get;set;} 
 public List<SelectOption> autoCollOptions{get;set;}
 public String hostedPageVersion{get;set;} 
 public List<SelectOption> hostedPages{get;set;}
 
 
 
    public ChargeBeeSettingController() {
     
     //chargebee_settings__c mhc = chargebee_settings__c.getInstance();
     setting = new CustomSettingProxy();
     overRideAllowed = isOverRideAllowed();
     autoCollection = autoCollection();
     autoCollOptions = new List<SelectOption>();
     autoCollOptions.add(new SelectOption('OFF','OFF'));
     autoCollOptions.add(new SelectOption('ON','ON'));
     hostedPageVersion = getHostedPageVersion();
     hostedPages = new List<SelectOption>();
     hostedPages.add(new SelectOption('V3','V3 Hostedpage'));
     hostedPages.add(new SelectOption('V2','V2 HostedPage'));
     
    }

public String getHostedPageVersion(){
     String temp = setting.siteSetting;
     if(temp != null){
         Map<String, String> b = (Map<String,String>) JSON.deserialize(temp, Map<String,String>.class);
         System.debug(b);
         if(b.get('useV3UpdatePayment') != null && b.get('useV3UpdatePayment').equals('V3')){
             hostedPageVersion = 'V3';
         }
         else{
             hostedPageVersion = 'V2';
         }
     }
     return hostedPageVersion;
 }
     
public String isOverRideAllowed(){
     String temp = setting.siteSetting;
     if(temp != null){
         Map<String, String> b = (Map<String,String>) JSON.deserialize(temp, Map<String,String>.class);
         System.debug(b);
         if(b.get('isOverRide') != null && b.get('isOverRide').equals('true')){
             overRideAllowed = 'Enabled';
         }
         else{
             overRideAllowed = 'Disabled';
         }
     }
     return overRideAllowed;
 }
 
 public String autoCollection(){
     String temp = setting.siteSetting;
     if(temp != null){
         Map<String, String> b = (Map<String,String>) JSON.deserialize(temp, Map<String,String>.class);
         System.debug(b);
         if(b.get('autoCollectionFlag') != null){
             autoCollection = b.get('autoCollectionFlag');
         }
         else{
             autoCollection = 'ON';
         }
     }
     return autoCollection;
 }
    
    

public class CustomSettingProxy {
        public String apikey {get;set;}
        public String chargebeeurl {get;set;}
        public String username {get;set;}
        public String siteSetting {get;set;}
        chargebee__c mhc{get;set;}
        
        public CustomSettingProxy() {
            try{
            /*
                List<String> fields1 = new List<String> {'API_Key__c', 'ChargeBee_URL__c','Settings_JSON__c','User_Name__c'};
                if(!FlsUtil.isPermitable(fields1,'Chargebee_Config__c'))
                {
                    redirectToError();
                }
                */
                //mhc = [select API_Key__c, ChargeBee_URL__c,Settings_JSON__c,User_Name__c from chargebee_settings__c ];
                mhc = chargebee__c.getOrgDefaults();
            }catch(Exception e){
                System.debug('-err---' + e);
            }
            System.debug('--->>' + mhc);
            this.apikey= mhc != null?mhc.API_Key__c:'';
            this.username = mhc != null?mhc.User_Name__c:'';
            this.chargebeeurl = mhc != null?mhc.ChargeBee_URL__c:'';
            this.siteSetting = mhc != null?mhc.Settings_JSON__c:null;
            
        }
        public PageReference redirectToError()
        {
           PageReference pageRef = new PageReference('/apex/error');
           pageRef.setRedirect(true);
           return pageRef; 
        }


        
         /*public void insertSetting() {
            try{    
                if(mhc != null){
                     mhc.API_Key__c=apikey;
                     mhc.User_Name__c=username;
                     mhc.ChargeBee_URL__c=chargebeeurl;
                     mhc.CB_Primary__c = 1;
                     mhc.Settings_JSON__c = siteSetting;
                     List<String> fields1 = new List<String> {'Subscription_Plan__c'};
                     if(!FlsUtil.isUpdate(fields1,'Chargebee_Config__c'))
                     {
                         redirectToError();
                     }
                     update mhc;
                }
                }catch(exception e)
                {
                    System.debug('err--->>' + e);
                }
        }*/

    }

   
   }