force-app/main/default/objects/Contact/fields/Auto_collection__c.field-meta.xml
<CustomField>
    <fullName>Auto_collection__c</fullName>
    <label>Auto collection</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>CB external id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CBCustomerTest.cls
@IsTest(SeeAllData = true) public with sharing class CBCustomerTest
{
     @IsTest(SeeAllData = true) public static void testCBCreate() 
     {
     
     PageReference pageRef = Page.CBNewCustomer;
     test.setCurrentPageReference(pageRef);
     pageRef.getParameters().put('id','00328000003Pcc4');
     pageRef.getParameters().put('url','/003/o');
     pageRef.getParameters().put('action','sync');
     CBNewCustomer cbu = new CBNewCustomer();
     Test.setMock(HttpCalloutMock.class, new MockCustGenerator());
     cbu.createCustomer();
     cbu.back();
     }
     
     @IsTest(SeeAllData = true) public static void testCBCreateNew() 
     {
     
     Contact cont = [select LastName, FirstName,Email, AccountId, MobilePhone, MailingStreet, MailingCity, MailingState, MailingCountry, MailingPostalCode, Auto_collection__c, External_Id__c from contact where id=:'0032800000xXAYx'];    
     cont.External_Id__c = null;
     update cont;
     
     PageReference pageRef = Page.CBNewCustomer;
     test.setCurrentPageReference(pageRef);
     pageRef.getParameters().put('id','0032800000xXAYx');
     pageRef.getParameters().put('url','/003/o');
     pageRef.getParameters().put('action','sync');     
     CBNewCustomer cbu = new CBNewCustomer();
     cbu.createCustomer();
     cbu.back();
     }
}